name: simple_alert
description: Multiple, customizable, responsive alerts with progress bars, action buttons, and more.
version: 1.0.0

repository: https://github.com/PresKhaled/simple-alert
issue_tracker: https://github.com/PresKhaled/simple-alert/issues

environment:
  sdk: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
